// main.js
// This is the main executable of the squid indexer.

// DataSourceBuilder will be used to make the object
// responsible for data retrieval settings.
import {DataSourceBuilder} from '@subsquid/evm-stream'
// To actually get the data and process it we'll use
// the unified `run` function.
import {run} from '@subsquid/batch-processor'
// TypeormDatabase is the class responsible for data storage.
import {TypeormDatabase} from '@subsquid/typeorm-store'
// usdcAbi is a utility module generated from the JSON ABI of the USDC contract.
// It contains methods for event decoding, direct RPC queries and some useful
// constants.
import * as usdcAbi from './abi/usdc'
// UsdcTransfer is a TypeORM model class of the usdc_transfer Postgres table.
// It is autogenerated from schema.graphql.
import {UsdcTransfer} from './model'

const USDC_CONTRACT_ADDRESS =
  '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48'

// First we configure data retrieval.
const dataSource = new DataSourceBuilder()
  // Pointing the data source to the SQD Network public Portal
  // dataset-specific URL. Portal handles both high speed retrieval
  // of historical data and keeping up with the real time updates
  // with low latency.
  .setPortal({
    url: 'https://portal.sqd.dev/datasets/ethereum-mainnet',

    // The maxBytes param will change the batch size, which can be useful
    // for optimizing disk IO. The default is 52_428_800 or 50Mb
    //maxBytes: 104_857_600, // 100Mb

    // Uncomment the line below if you don't want to handle
    // indexer restarts on non-2XX HTTP responses.
    //http: { retryAttempts: Infinity },
  })
  // .addXXX() methods request data items. In this case we're asking for
  // Transfer(address,address,uint256) event logs emitted by the USDC contract.
  //
  // We could have omitted the "address" filter to get Transfer events from
  // all contracts, or the "topic0" filter to get all events from the USDC
  // contract, or both to get all event logs chainwide. We also could have
  // requested some related data, such as the parent transaction or its traces.
  //
  // Other .addXXX() methods (.addTransaction(), .addTrace(), .addStateDiff()
  // on EVM) are similarly feature-rich.
  .addLog({
    where: {
      address: [USDC_CONTRACT_ADDRESS],
      topic0: [usdcAbi.events.Transfer.topic],
    },
    include: {
      //transaction: true,
    },
//    range: { from: 6_082_465 },
    range: { from: 24_052_465 },
  })
  // .setFields() is for choosing data fields for the selected data items.
  // Here we're requesting hashes of parent transactions for all event logs.
  .setFields({
    log: {
      transactionHash: true,
    },
  })
  .build()

// TypeormDatabase objects store the data to Postgres. They are capable of
// handling the rollbacks that occur due to blockchain forks.
//
// There are also Database classes for storing data to files and BigQuery
// datasets.
const db = new TypeormDatabase({supportHotBlocks: true})

// The run() call executes the data processing. Its last argument is
// the handler function that is executed once on each batch of data. Processor
// object provides the data via "ctx.blocks". However, the handler can contain
// arbitrary TypeScript code, so it's OK to bring in extra data from IPFS,
// direct RPC calls, external APIs etc.
run(dataSource, db, async (ctx) => {
  // Making the container to hold that which will become the rows of the
  // usdc_transfer database table while processing the batch. We'll insert them
  // all at once at the end, massively saving IO bandwidth.
  const transfers: UsdcTransfer[] = []

  // The data retrieved from the SQD Network gatewat and/or the RPC endpoint
  // is supplied via ctx.blocks
  for (let block of ctx.blocks) {
    // On EVM, each block has four iterables - logs, transactions, traces,
    // stateDiffs
    for (let log of block.logs) {
      if (log.address === USDC_CONTRACT_ADDRESS &&
          log.topics[0] === usdcAbi.events.Transfer.topic) {
        // SQD's very own EVM codec at work - about 20 times faster than ethers
        let {from, to, value} = usdcAbi.events.Transfer.decode(log)
        transfers.push(new UsdcTransfer({
          id: `${block.header.number}-${log.transactionIndex}-${log.logIndex}`,
          block: block.header.number, // the height
          from,
          to,
          value,
          txnHash: log.transactionHash
        }))
      }
    }
  }

  // Just one insert per batch!
  await ctx.store.insert(transfers)
})
